
// ==================================================================
// UsersConnectLCHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul
{
  public partial class UsersConnectLCClientHandlers : global::Sungero.Reporting.ReportClientHandlers
  {
    private global::Sungero.ClassModul.IUsersConnectLC UsersConnectLC
    {
      get { return (global::Sungero.ClassModul.IUsersConnectLC)this._Report; }
    }

    public UsersConnectLCClientHandlers(global::Sungero.ClassModul.IUsersConnectLC report) : base(report) { }
  }
}
