
// ==================================================================
// TrainingReportConnectedDepartmentOnEDMHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul
{
  public partial class TrainingReportConnectedDepartmentOnEDMClientHandlers : global::Sungero.Reporting.ReportClientHandlers
  {
    private global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDM TrainingReportConnectedDepartmentOnEDM
    {
      get { return (global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDM)this._Report; }
    }

    public TrainingReportConnectedDepartmentOnEDMClientHandlers(global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDM report) : base(report) { }
  }
}
