
// ==================================================================
// TrainingReportAcquaintanceAssignedParticipantsListHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul
{
  public partial class TrainingReportAcquaintanceAssignedParticipantsListClientHandlers : global::Sungero.Reporting.ReportClientHandlers
  {
    private global::Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList TrainingReportAcquaintanceAssignedParticipantsList
    {
      get { return (global::Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList)this._Report; }
    }

    public TrainingReportAcquaintanceAssignedParticipantsListClientHandlers(global::Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList report) : base(report) { }
  }
}
