
// ==================================================================
// EmployeeReportHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul
{
  public partial class EmployeeReportClientHandlers : global::Sungero.Reporting.ReportClientHandlers
  {
    private global::Sungero.ClassModul.IEmployeeReport EmployeeReport
    {
      get { return (global::Sungero.ClassModul.IEmployeeReport)this._Report; }
    }

    public EmployeeReportClientHandlers(global::Sungero.ClassModul.IEmployeeReport report) : base(report) { }
  }
}
