
// ==================================================================
// TrainingReportDepsartmentsAssignmentComplitionHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul
{
  public partial class TrainingReportDepsartmentsAssignmentComplitionClientHandlers : global::Sungero.Reporting.ReportClientHandlers
  {
    private global::Sungero.ClassModul.ITrainingReportDepsartmentsAssignmentComplition TrainingReportDepsartmentsAssignmentComplition
    {
      get { return (global::Sungero.ClassModul.ITrainingReportDepsartmentsAssignmentComplition)this._Report; }
    }

    public TrainingReportDepsartmentsAssignmentComplitionClientHandlers(global::Sungero.ClassModul.ITrainingReportDepsartmentsAssignmentComplition report) : base(report) { }
  }
}
