
// ==================================================================
// TrainingReportDepsartmentsAssignmentComplition.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Client
{
  public class TrainingReportDepsartmentsAssignmentComplition : global::Sungero.Reporting.Client.Report, global::Sungero.ClassModul.ITrainingReportDepsartmentsAssignmentComplition
  {
    public static readonly new global::System.Guid ClassTypeGuid = new global::System.Guid("384f4625-c282-43e4-896d-9b352a351de0");

    protected override global::System.Guid ReportTypeId
    {
      get { return ClassTypeGuid; }
    }



    public global::System.Nullable<global::System.DateTime> ReportDate
    {
      get
      {
          return this.GetParameterValue("ReportDate") as global::System.Nullable<global::System.DateTime>;
      }

      set
      {
        this.SetParameterValue("ReportDate", value);
      }
    }

    public global::System.String ParamsDescription
    {
      get
      {
          return this.GetParameterValue("ParamsDescription") as global::System.String;
      }

      set
      {
        this.SetParameterValue("ParamsDescription", value);
      }
    }

    public global::System.Nullable<global::System.DateTime> PeriodBegin
    {
      get
      {
          return this.GetParameterValue("PeriodBegin") as global::System.Nullable<global::System.DateTime>;
      }

      set
      {
        this.SetParameterValue("PeriodBegin", value);
      }
    }

    public global::System.Nullable<global::System.DateTime> PeriodEnd
    {
      get
      {
          return this.GetParameterValue("PeriodEnd") as global::System.Nullable<global::System.DateTime>;
      }

      set
      {
        this.SetParameterValue("PeriodEnd", value);
      }
    }

    public global::DirRX.CustomHRSolution.IBusinessUnit BusinessUnit
    {
      get
      {
          return this.GetParameterValue("BusinessUnit") as global::DirRX.CustomHRSolution.IBusinessUnit;
      }

      set
      {
        this.SetParameterValue("BusinessUnit", value);
      }
    }

    public global::System.String DetailedReportLink
    {
      get
      {
          return this.GetParameterValue("DetailedReportLink") as global::System.String;
      }

      set
      {
        this.SetParameterValue("DetailedReportLink", value);
      }
    }

    public global::System.Nullable<global::System.Boolean> WithSubstitution
    {
      get
      {
          return this.GetParameterValue("WithSubstitution") as global::System.Nullable<global::System.Boolean>;
      }

      set
      {
        this.SetParameterValue("WithSubstitution", value);
      }
    }

    public global::System.Nullable<global::System.Boolean> Unwrap
    {
      get
      {
          return this.GetParameterValue("Unwrap") as global::System.Nullable<global::System.Boolean>;
      }

      set
      {
        this.SetParameterValue("Unwrap", value);
      }
    }

    public global::System.String WidgetParameter
    {
      get
      {
          return this.GetParameterValue("WidgetParameter") as global::System.String;
      }

      set
      {
        this.SetParameterValue("WidgetParameter", value);
      }
    }

    public global::DirRX.CustomHRSolution.IDepartment Department
    {
      get
      {
          return this.GetParameterValue("Department") as global::DirRX.CustomHRSolution.IDepartment;
      }

      set
      {
        this.SetParameterValue("Department", value);
      }
    }

    public global::System.Nullable<global::System.Int32> BusinessUnitId
    {
      get
      {
          return this.GetParameterValue("BusinessUnitId") as global::System.Nullable<global::System.Int32>;
      }

      set
      {
        this.SetParameterValue("BusinessUnitId", value);
      }
    }

    public global::System.String ReportSessionId
    {
      get
      {
          return this.GetParameterValue("ReportSessionId") as global::System.String;
      }

      set
      {
        this.SetParameterValue("ReportSessionId", value);
      }
    }

      private Sungero.Reporting.Shared.CollectionAdapter<global::System.Nullable<global::System.Int32>> _DepartmentIdAdapter;

    public Sungero.Reporting.Shared.CollectionAdapter<global::System.Nullable<global::System.Int32>> DepartmentId
    {
      get
      {
          if(this._DepartmentIdAdapter == null)
            this._DepartmentIdAdapter = new Sungero.Reporting.Shared.CollectionAdapter<global::System.Nullable<global::System.Int32>>(this, "DepartmentId");
          return this._DepartmentIdAdapter;
      }

    }


    public TrainingReportDepsartmentsAssignmentComplition()
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.ClassModul.TrainingReportDepsartmentsAssignmentComplitionClientHandlers");
      this.Handlers = type != null
        ? global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this })
        : new global::Sungero.ClassModul.TrainingReportDepsartmentsAssignmentComplitionClientHandlers(this);
    }
  }
}

// ==================================================================
// TrainingReportDepsartmentsAssignmentComplitionRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Client
{ 
  public class TrainingReportDepsartmentsAssignmentComplitionRepositoryImplementer<T> : 
      global::Sungero.Reporting.Client.ReportRepositoryImplementer<T>,
      global::Sungero.ClassModul.ITrainingReportDepsartmentsAssignmentComplitionRepositoryImplementer<T>
      where T : global::Sungero.ClassModul.ITrainingReportDepsartmentsAssignmentComplition
    {
    }
}
