
// ==================================================================
// UsersConnectLCResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Shared.Reports.UsersConnectLC
{
  public class UsersConnectLCResources : global::Sungero.ClassModul.IUsersConnectLCResources
  {
  }
}
