
// ==================================================================
// TrainingReportDocumentsEmployeeResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Shared.Reports.TrainingReportDocumentsEmployee
{
  public class TrainingReportDocumentsEmployeeResources : global::Sungero.ClassModul.ITrainingReportDocumentsEmployeeResources
  {
  }
}
