
// ==================================================================
// TrainingReportAcquaintanceAssignedParticipantsList.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Client
{
  public class TrainingReportAcquaintanceAssignedParticipantsList : global::Sungero.Reporting.Client.Report, global::Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList
  {
    public static readonly new global::System.Guid ClassTypeGuid = new global::System.Guid("0deeb0ac-d0a4-4a9f-8c7a-1e92088ae2ff");

    protected override global::System.Guid ReportTypeId
    {
      get { return ClassTypeGuid; }
    }



    public global::DirRX.LRD.ILocalRegulationDocument Document
    {
      get
      {
          return this.GetParameterValue("Document") as global::DirRX.LRD.ILocalRegulationDocument;
      }

      set
      {
        this.SetParameterValue("Document", value);
      }
    }

    public global::System.String ReportSessionId
    {
      get
      {
          return this.GetParameterValue("ReportSessionId") as global::System.String;
      }

      set
      {
        this.SetParameterValue("ReportSessionId", value);
      }
    }

    public global::System.String Title
    {
      get
      {
          return this.GetParameterValue("Title") as global::System.String;
      }

      set
      {
        this.SetParameterValue("Title", value);
      }
    }

    public global::System.String ReportDate
    {
      get
      {
          return this.GetParameterValue("ReportDate") as global::System.String;
      }

      set
      {
        this.SetParameterValue("ReportDate", value);
      }
    }

    public global::System.String DocumentName
    {
      get
      {
          return this.GetParameterValue("DocumentName") as global::System.String;
      }

      set
      {
        this.SetParameterValue("DocumentName", value);
      }
    }

    public global::System.String BusinessUnit
    {
      get
      {
          return this.GetParameterValue("BusinessUnit") as global::System.String;
      }

      set
      {
        this.SetParameterValue("BusinessUnit", value);
      }
    }

    public global::DirRX.CustomHRSolution.IListsLNAForRecruitmentAndTransfer ListLNA
    {
      get
      {
          return this.GetParameterValue("ListLNA") as global::DirRX.CustomHRSolution.IListsLNAForRecruitmentAndTransfer;
      }

      set
      {
        this.SetParameterValue("ListLNA", value);
      }
    }

    public global::System.Nullable<global::System.Boolean> IsList
    {
      get
      {
          return this.GetParameterValue("IsList") as global::System.Nullable<global::System.Boolean>;
      }

      set
      {
        this.SetParameterValue("IsList", value);
      }
    }


    public TrainingReportAcquaintanceAssignedParticipantsList()
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.ClassModul.TrainingReportAcquaintanceAssignedParticipantsListClientHandlers");
      this.Handlers = type != null
        ? global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this })
        : new global::Sungero.ClassModul.TrainingReportAcquaintanceAssignedParticipantsListClientHandlers(this);
    }
  }
}

// ==================================================================
// TrainingReportAcquaintanceAssignedParticipantsListRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Client
{ 
  public class TrainingReportAcquaintanceAssignedParticipantsListRepositoryImplementer<T> : 
      global::Sungero.Reporting.Client.ReportRepositoryImplementer<T>,
      global::Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsListRepositoryImplementer<T>
      where T : global::Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList
    {
    }
}
