
// ==================================================================
// ModuleFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Functions
{
  internal static partial class Module
  {
    internal static class Remote
    {
      /// <redirect project="Sungero.ClassModul.Server" type="Sungero.ClassModul.Server.ModuleFunctions" />
      internal static global::System.String ConvertDocToPdf(global::Sungero.Docflow.IInternalDocumentBase document)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::System.String>(
          global::System.Guid.Parse("b8491e9e-084d-4fcb-b33c-1e421f4383d6"),
          "ConvertDocToPdf(global::Sungero.Docflow.IInternalDocumentBase)", document);
      }
      /// <redirect project="Sungero.ClassModul.Server" type="Sungero.ClassModul.Server.ModuleFunctions" />
      internal static global::System.Boolean ChecktDocForFormatPdf(global::Sungero.Docflow.IInternalDocumentBase document)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::System.Boolean>(
          global::System.Guid.Parse("b8491e9e-084d-4fcb-b33c-1e421f4383d6"),
          "ChecktDocForFormatPdf(global::Sungero.Docflow.IInternalDocumentBase)", document);
      }

    }
    private static object GetFunctionsContainer()
    {
      return new global::Sungero.ClassModul.Shared.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType, global::Sungero.Metadata.ModuleMetadata finalModuleMetadatda)
    {
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      var methodInfo = moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static);
      return global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, null, null);
    }
  }
}

// ==================================================================
// ModuleHyperlinks.g.cs
// ==================================================================

namespace Sungero.ClassModul
{
  public static class ClassModulClientFunctionHyperlinksExtensions
  {
  }
}

// ==================================================================
// ModuleResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Shared
{
  public class ModuleResources : global::Sungero.ClassModul.IModuleResources
  {
  }
}

// ==================================================================
// ModuleFoldersFilterStates.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Shared
{
}

// ==================================================================
// ModuleSharedPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Shared
{
  public partial class ModuleSharedPublicFunctions : global::Sungero.ClassModul.Shared.IModuleSharedPublicFunctions
  {
    public global::System.Boolean Remote_ChecktDocForFormatPdf(global::Sungero.Docflow.IInternalDocumentBase document)
    {
      return global::Sungero.ClassModul.Functions.Module.Remote.ChecktDocForFormatPdf(document);
    }
    public global::System.String Remote_ConvertDocToPdf(global::Sungero.Docflow.IInternalDocumentBase document)
    {
      return global::Sungero.ClassModul.Functions.Module.Remote.ConvertDocToPdf(document);
    }
  }
}

// ==================================================================
// ModuleWidgetParameters.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Shared
{  
}
