
// ==================================================================
// TrainingReportConnectedDepartmentOnEDM.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Client
{
  public class TrainingReportConnectedDepartmentOnEDM : global::Sungero.Reporting.Client.Report, global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDM
  {
    public static readonly new global::System.Guid ClassTypeGuid = new global::System.Guid("05f7f8e2-cb64-4a45-b31e-119119b3ec76");

    protected override global::System.Guid ReportTypeId
    {
      get { return ClassTypeGuid; }
    }



    public global::System.Nullable<global::System.DateTime> DateReport
    {
      get
      {
          return this.GetParameterValue("DateReport") as global::System.Nullable<global::System.DateTime>;
      }

      set
      {
        this.SetParameterValue("DateReport", value);
      }
    }

    public global::System.String ReportSessionId
    {
      get
      {
          return this.GetParameterValue("ReportSessionId") as global::System.String;
      }

      set
      {
        this.SetParameterValue("ReportSessionId", value);
      }
    }

    public global::System.Nullable<global::System.Double> PercentEmpValidSIg
    {
      get
      {
          return this.GetParameterValue("PercentEmpValidSIg") as global::System.Nullable<global::System.Double>;
      }

      set
      {
        this.SetParameterValue("PercentEmpValidSIg", value);
      }
    }

    public global::System.Nullable<global::System.Double> PercentEmpAgreToEDM
    {
      get
      {
          return this.GetParameterValue("PercentEmpAgreToEDM") as global::System.Nullable<global::System.Double>;
      }

      set
      {
        this.SetParameterValue("PercentEmpAgreToEDM", value);
      }
    }


    public TrainingReportConnectedDepartmentOnEDM()
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.ClassModul.TrainingReportConnectedDepartmentOnEDMClientHandlers");
      this.Handlers = type != null
        ? global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this })
        : new global::Sungero.ClassModul.TrainingReportConnectedDepartmentOnEDMClientHandlers(this);
    }
  }
}

// ==================================================================
// TrainingReportConnectedDepartmentOnEDMRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Client
{ 
  public class TrainingReportConnectedDepartmentOnEDMRepositoryImplementer<T> : 
      global::Sungero.Reporting.Client.ReportRepositoryImplementer<T>,
      global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDMRepositoryImplementer<T>
      where T : global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDM
    {
    }
}
