
// ==================================================================
// TrainingReportDocumentsEmployeeHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul
{
  public partial class TrainingReportDocumentsEmployeeClientHandlers : global::Sungero.Reporting.ReportClientHandlers
  {
    private global::Sungero.ClassModul.ITrainingReportDocumentsEmployee TrainingReportDocumentsEmployee
    {
      get { return (global::Sungero.ClassModul.ITrainingReportDocumentsEmployee)this._Report; }
    }

    public TrainingReportDocumentsEmployeeClientHandlers(global::Sungero.ClassModul.ITrainingReportDocumentsEmployee report) : base(report) { }
  }
}
