
// ==================================================================
// TrainingReportConnectedDepartmentOnEDM.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Server
{
  public class TrainingReportConnectedDepartmentOnEDM : global::Sungero.Reporting.Server.Report, global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDM
  {
    public static readonly new global::System.Guid ClassTypeGuid = new global::System.Guid("05f7f8e2-cb64-4a45-b31e-119119b3ec76");

    protected override global::System.Guid ReportTypeId
    {
      get { return ClassTypeGuid; }
    }


    protected override void FillDataSources(global::FastReport.Report report)
    {
      base.FillDataSources(report);
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.ClassModul.TrainingReportConnectedDepartmentOnEDMServerHandlers");
      if (type != null)
      {
      }
      else
      {
      }
    }


    public global::System.Nullable<global::System.DateTime> DateReport
    {
      get
      {
          return this.GetParameterValue("DateReport") as global::System.Nullable<global::System.DateTime>;
      }

      set
      {
        this.SetParameterValue("DateReport", value);
      }
    }

    public global::System.String ReportSessionId
    {
      get
      {
          return this.GetParameterValue("ReportSessionId") as global::System.String;
      }

      set
      {
        this.SetParameterValue("ReportSessionId", value);
      }
    }

    public global::System.Nullable<global::System.Double> PercentEmpValidSIg
    {
      get
      {
          return this.GetParameterValue("PercentEmpValidSIg") as global::System.Nullable<global::System.Double>;
      }

      set
      {
        this.SetParameterValue("PercentEmpValidSIg", value);
      }
    }

    public global::System.Nullable<global::System.Double> PercentEmpAgreToEDM
    {
      get
      {
          return this.GetParameterValue("PercentEmpAgreToEDM") as global::System.Nullable<global::System.Double>;
      }

      set
      {
        this.SetParameterValue("PercentEmpAgreToEDM", value);
      }
    }


    public TrainingReportConnectedDepartmentOnEDM()
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.ClassModul.TrainingReportConnectedDepartmentOnEDMServerHandlers");
      this.Handlers = type != null
        ? global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this })
        : new global::Sungero.ClassModul.TrainingReportConnectedDepartmentOnEDMServerHandlers(this);
    }
  }
}

// ==================================================================
// TrainingReportConnectedDepartmentOnEDMHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul
{
  public partial class TrainingReportConnectedDepartmentOnEDMServerHandlers : global::Sungero.Reporting.ReportServerHandlers
  {
    private global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDM TrainingReportConnectedDepartmentOnEDM
    {
      get { return (global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDM)this._Report; }
    }

    public TrainingReportConnectedDepartmentOnEDMServerHandlers(global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDM report) : base(report) { }
  }
}

// ==================================================================
// TrainingReportConnectedDepartmentOnEDMRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Server
{
  public class TrainingReportConnectedDepartmentOnEDMRepositoryImplementer<T> : 
    global::Sungero.Reporting.Server.ReportRepositoryImplementer<T>,
    global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDMRepositoryImplementer<T>
    where T : global::Sungero.ClassModul.ITrainingReportConnectedDepartmentOnEDM 
  {
  }
}

// ==================================================================
// TrainingReportConnectedDepartmentOnEDMQueries.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Queries
{
  public class TrainingReportConnectedDepartmentOnEDM
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("Sungero.ClassModul.Server.Reports.TrainingReportConnectedDepartmentOnEDM.TrainingReportConnectedDepartmentOnEDMQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
    public static string CreateTableConnectedDepartmentOnEDM
    {
       get { return resolver.GetQuery("CreateTableConnectedDepartmentOnEDM"); }
    }
    public static string SelectDataFromTable
    {
       get { return resolver.GetQuery("SelectDataFromTable"); }
    }
  }
}
