
// ==================================================================
// TraningReportTasksWithAttachmentsHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul
{
  public partial class TraningReportTasksWithAttachmentsClientHandlers : global::Sungero.Reporting.ReportClientHandlers
  {
    private global::Sungero.ClassModul.ITraningReportTasksWithAttachments TraningReportTasksWithAttachments
    {
      get { return (global::Sungero.ClassModul.ITraningReportTasksWithAttachments)this._Report; }
    }

    public TraningReportTasksWithAttachmentsClientHandlers(global::Sungero.ClassModul.ITraningReportTasksWithAttachments report) : base(report) { }
  }
}
