
// ==================================================================
// TrainingReportAcquaintanceAssignedParticipantsListResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Shared.Reports.TrainingReportAcquaintanceAssignedParticipantsList
{
  public class TrainingReportAcquaintanceAssignedParticipantsListResources : global::Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsListResources
  {
    public virtual global::CommonLibrary.LocalizedString FullName
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList) , "FullName");
      }
    }

    public virtual global::CommonLibrary.LocalizedString FullNameFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList), "FullName", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString PersonnelNumber
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList) , "PersonnelNumber");
      }
    }

    public virtual global::CommonLibrary.LocalizedString PersonnelNumberFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList), "PersonnelNumber", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString Consent
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList) , "Consent");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ConsentFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList), "Consent", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString Department
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList) , "Department");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DepartmentFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList), "Department", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString JobTitle
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList) , "JobTitle");
      }
    }

    public virtual global::CommonLibrary.LocalizedString JobTitleFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList), "JobTitle", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString LRDList
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList) , "LRDList");
      }
    }

    public virtual global::CommonLibrary.LocalizedString LRDListFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList), "LRDList", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString GeneralReportTitle
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList) , "GeneralReportTitle");
      }
    }

    public virtual global::CommonLibrary.LocalizedString GeneralReportTitleFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList), "GeneralReportTitle", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString LRDListsPageTitle
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList) , "LRDListsPageTitle");
      }
    }

    public virtual global::CommonLibrary.LocalizedString LRDListsPageTitleFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList), "LRDListsPageTitle", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString TypicalPosition
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList) , "TypicalPosition");
      }
    }

    public virtual global::CommonLibrary.LocalizedString TypicalPositionFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList), "TypicalPosition", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString TypicalPositionId
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList) , "TypicalPositionId");
      }
    }

    public virtual global::CommonLibrary.LocalizedString TypicalPositionIdFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList), "TypicalPositionId", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString JobTitleId
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList) , "JobTitleId");
      }
    }

    public virtual global::CommonLibrary.LocalizedString JobTitleIdFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(Sungero.ClassModul.ITrainingReportAcquaintanceAssignedParticipantsList), "JobTitleId", false, args);
    }

  }
}
