
// ==================================================================
// TrainingReportDocumentsEmployee.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Server
{
  public class TrainingReportDocumentsEmployee : global::Sungero.Reporting.Server.Report, global::Sungero.ClassModul.ITrainingReportDocumentsEmployee
  {
    public static readonly new global::System.Guid ClassTypeGuid = new global::System.Guid("05052fe5-9c6c-48fe-bad8-b4945c78a296");

    protected override global::System.Guid ReportTypeId
    {
      get { return ClassTypeGuid; }
    }


    protected override void FillDataSources(global::FastReport.Report report)
    {
      base.FillDataSources(report);
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.ClassModul.TrainingReportDocumentsEmployeeServerHandlers");
      if (type != null)
      {
      }
      else
      {
      }
    }


    public global::System.Nullable<global::System.Int32> EmployeeId
    {
      get
      {
          return this.GetParameterValue("EmployeeId") as global::System.Nullable<global::System.Int32>;
      }

      set
      {
        this.SetParameterValue("EmployeeId", value);
      }
    }

    public global::System.Nullable<global::System.DateTime> DateStart
    {
      get
      {
          return this.GetParameterValue("DateStart") as global::System.Nullable<global::System.DateTime>;
      }

      set
      {
        this.SetParameterValue("DateStart", value);
      }
    }

    public global::System.Nullable<global::System.DateTime> DateEnd
    {
      get
      {
          return this.GetParameterValue("DateEnd") as global::System.Nullable<global::System.DateTime>;
      }

      set
      {
        this.SetParameterValue("DateEnd", value);
      }
    }


    public TrainingReportDocumentsEmployee()
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.ClassModul.TrainingReportDocumentsEmployeeServerHandlers");
      this.Handlers = type != null
        ? global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this })
        : new global::Sungero.ClassModul.TrainingReportDocumentsEmployeeServerHandlers(this);
    }
  }
}

// ==================================================================
// TrainingReportDocumentsEmployeeHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul
{
  public partial class TrainingReportDocumentsEmployeeServerHandlers : global::Sungero.Reporting.ReportServerHandlers
  {
    private global::Sungero.ClassModul.ITrainingReportDocumentsEmployee TrainingReportDocumentsEmployee
    {
      get { return (global::Sungero.ClassModul.ITrainingReportDocumentsEmployee)this._Report; }
    }

    public TrainingReportDocumentsEmployeeServerHandlers(global::Sungero.ClassModul.ITrainingReportDocumentsEmployee report) : base(report) { }
  }
}

// ==================================================================
// TrainingReportDocumentsEmployeeRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Server
{
  public class TrainingReportDocumentsEmployeeRepositoryImplementer<T> : 
    global::Sungero.Reporting.Server.ReportRepositoryImplementer<T>,
    global::Sungero.ClassModul.ITrainingReportDocumentsEmployeeRepositoryImplementer<T>
    where T : global::Sungero.ClassModul.ITrainingReportDocumentsEmployee 
  {
  }
}

// ==================================================================
// TrainingReportDocumentsEmployeeQueries.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Queries
{
  public class TrainingReportDocumentsEmployee
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("Sungero.ClassModul.Server.Reports.TrainingReportDocumentsEmployee.TrainingReportDocumentsEmployeeQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
    public static string SelectDocuments
    {
       get { return resolver.GetQuery("SelectDocuments"); }
    }
  }
}
