
// ==================================================================
// TrainingReportDepsartmentsAssignmentComplitionResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Shared.Reports.TrainingReportDepsartmentsAssignmentComplition
{
  public class TrainingReportDepsartmentsAssignmentComplitionResources : global::Sungero.ClassModul.ITrainingReportDepsartmentsAssignmentComplitionResources
  {
  }
}
