
// ==================================================================
// TraningReportTasksWithAttachments.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Server
{
  public class TraningReportTasksWithAttachments : global::Sungero.Reporting.Server.Report, global::Sungero.ClassModul.ITraningReportTasksWithAttachments
  {
    public static readonly new global::System.Guid ClassTypeGuid = new global::System.Guid("842ccc2e-1129-495e-afa0-59171d4d37ae");

    protected override global::System.Guid ReportTypeId
    {
      get { return ClassTypeGuid; }
    }


    protected override void FillDataSources(global::FastReport.Report report)
    {
      base.FillDataSources(report);
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.ClassModul.TraningReportTasksWithAttachmentsServerHandlers");
      if (type != null)
      {
        report.RegisterData(
          (global::System.Collections.IEnumerable)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(type.GetMethod("GetDocuments"), this.Handlers, null),
          "Documents");

      }
      else
      {
        report.RegisterData(
          ((global::Sungero.ClassModul.TraningReportTasksWithAttachmentsServerHandlers)this.Handlers).GetDocuments(),
          "Documents");

      }
    }


    public global::System.Nullable<global::System.DateTime> StartDate
    {
      get
      {
          return this.GetParameterValue("StartDate") as global::System.Nullable<global::System.DateTime>;
      }

      set
      {
        this.SetParameterValue("StartDate", value);
      }
    }

    public global::System.Nullable<global::System.DateTime> EndDate
    {
      get
      {
          return this.GetParameterValue("EndDate") as global::System.Nullable<global::System.DateTime>;
      }

      set
      {
        this.SetParameterValue("EndDate", value);
      }
    }


    public TraningReportTasksWithAttachments()
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.ClassModul.TraningReportTasksWithAttachmentsServerHandlers");
      this.Handlers = type != null
        ? global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this })
        : new global::Sungero.ClassModul.TraningReportTasksWithAttachmentsServerHandlers(this);
    }
  }
}

// ==================================================================
// TraningReportTasksWithAttachmentsHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul
{
  public partial class TraningReportTasksWithAttachmentsServerHandlers : global::Sungero.Reporting.ReportServerHandlers
  {
    private global::Sungero.ClassModul.ITraningReportTasksWithAttachments TraningReportTasksWithAttachments
    {
      get { return (global::Sungero.ClassModul.ITraningReportTasksWithAttachments)this._Report; }
    }

    public TraningReportTasksWithAttachmentsServerHandlers(global::Sungero.ClassModul.ITraningReportTasksWithAttachments report) : base(report) { }
  }
}

// ==================================================================
// TraningReportTasksWithAttachmentsRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Server
{
  public class TraningReportTasksWithAttachmentsRepositoryImplementer<T> : 
    global::Sungero.Reporting.Server.ReportRepositoryImplementer<T>,
    global::Sungero.ClassModul.ITraningReportTasksWithAttachmentsRepositoryImplementer<T>
    where T : global::Sungero.ClassModul.ITraningReportTasksWithAttachments 
  {
  }
}

// ==================================================================
// TraningReportTasksWithAttachmentsQueries.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Queries
{
  public class TraningReportTasksWithAttachments
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("Sungero.ClassModul.Server.Reports.TraningReportTasksWithAttachments.TraningReportTasksWithAttachmentsQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
    public static string TasksForReport
    {
       get { return resolver.GetQuery("TasksForReport"); }
    }
  }
}
