
// ==================================================================
// Module.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Client
{
  public partial class ClassModulModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("b8491e9e-084d-4fcb-b33c-1e421f4383d6"); }
    }

    public override string Name
    {
      get { return "Sungero.ClassModul"; }
    }

    public override void RegisterTypes()
    {



      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.ClassModul.Client.IModuleClientPublicFunctions, global::Sungero.ClassModul.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::Sungero.ClassModul.Shared.IModuleSharedPublicFunctions, global::Sungero.ClassModul.Shared.ModuleSharedPublicFunctions>();
    }
  }
}
