
// ==================================================================
// UsersConnectLC.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Server
{
  public class UsersConnectLC : global::Sungero.Reporting.Server.Report, global::Sungero.ClassModul.IUsersConnectLC
  {
    public static readonly new global::System.Guid ClassTypeGuid = new global::System.Guid("6f9c79f4-8d59-4b9c-94f0-aaa9a5a92917");

    protected override global::System.Guid ReportTypeId
    {
      get { return ClassTypeGuid; }
    }


    protected override void FillDataSources(global::FastReport.Report report)
    {
      base.FillDataSources(report);
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.ClassModul.UsersConnectLCServerHandlers");
      if (type != null)
      {
        report.RegisterData(
          (global::System.Collections.IEnumerable)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(type.GetMethod("GetEmployees"), this.Handlers, null),
          "Employees");

      }
      else
      {
        report.RegisterData(
          ((global::Sungero.ClassModul.UsersConnectLCServerHandlers)this.Handlers).GetEmployees(),
          "Employees");

      }
    }


    public global::System.Nullable<global::System.DateTime> ReportDate
    {
      get
      {
          return this.GetParameterValue("ReportDate") as global::System.Nullable<global::System.DateTime>;
      }

      set
      {
        this.SetParameterValue("ReportDate", value);
      }
    }

    public global::System.Nullable<global::System.Boolean> NoConnect
    {
      get
      {
          return this.GetParameterValue("NoConnect") as global::System.Nullable<global::System.Boolean>;
      }

      set
      {
        this.SetParameterValue("NoConnect", value);
      }
    }

    public global::System.Nullable<global::System.Int32> CountCompany
    {
      get
      {
          return this.GetParameterValue("CountCompany") as global::System.Nullable<global::System.Int32>;
      }

      set
      {
        this.SetParameterValue("CountCompany", value);
      }
    }

    public global::System.Nullable<global::System.Int32> CountDepartment
    {
      get
      {
          return this.GetParameterValue("CountDepartment") as global::System.Nullable<global::System.Int32>;
      }

      set
      {
        this.SetParameterValue("CountDepartment", value);
      }
    }

    public global::System.String DepartmentName
    {
      get
      {
          return this.GetParameterValue("DepartmentName") as global::System.String;
      }

      set
      {
        this.SetParameterValue("DepartmentName", value);
      }
    }

    public global::System.Nullable<global::System.Int32> MaxCountEmployee
    {
      get
      {
          return this.GetParameterValue("MaxCountEmployee") as global::System.Nullable<global::System.Int32>;
      }

      set
      {
        this.SetParameterValue("MaxCountEmployee", value);
      }
    }

    public global::DirRX.CustomHRSolution.IBusinessUnit BusinessUnit
    {
      get
      {
          return this.GetParameterValue("BusinessUnit") as global::DirRX.CustomHRSolution.IBusinessUnit;
      }

      set
      {
        this.SetParameterValue("BusinessUnit", value);
      }
    }

    public global::DirRX.CustomHRSolution.IDepartment Department
    {
      get
      {
          return this.GetParameterValue("Department") as global::DirRX.CustomHRSolution.IDepartment;
      }

      set
      {
        this.SetParameterValue("Department", value);
      }
    }

    public global::System.Nullable<global::System.Boolean> FilterDepartmentsForBusinessUnits
    {
      get
      {
          return this.GetParameterValue("FilterDepartmentsForBusinessUnits") as global::System.Nullable<global::System.Boolean>;
      }

      set
      {
        this.SetParameterValue("FilterDepartmentsForBusinessUnits", value);
      }
    }

    public global::System.Nullable<global::System.Boolean> FilterEmployeesForBusinessUniit
    {
      get
      {
          return this.GetParameterValue("FilterEmployeesForBusinessUniit") as global::System.Nullable<global::System.Boolean>;
      }

      set
      {
        this.SetParameterValue("FilterEmployeesForBusinessUniit", value);
      }
    }

    public global::System.Nullable<global::System.Boolean> FilterinEmployeeForDepartment
    {
      get
      {
          return this.GetParameterValue("FilterinEmployeeForDepartment") as global::System.Nullable<global::System.Boolean>;
      }

      set
      {
        this.SetParameterValue("FilterinEmployeeForDepartment", value);
      }
    }


    public UsersConnectLC()
    {
      var type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve("Sungero.ClassModul.UsersConnectLCServerHandlers");
      this.Handlers = type != null
        ? global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(type, new object[] { this })
        : new global::Sungero.ClassModul.UsersConnectLCServerHandlers(this);
    }
  }
}

// ==================================================================
// UsersConnectLCHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul
{
  public partial class UsersConnectLCServerHandlers : global::Sungero.Reporting.ReportServerHandlers
  {
    private global::Sungero.ClassModul.IUsersConnectLC UsersConnectLC
    {
      get { return (global::Sungero.ClassModul.IUsersConnectLC)this._Report; }
    }

    public UsersConnectLCServerHandlers(global::Sungero.ClassModul.IUsersConnectLC report) : base(report) { }
  }
}

// ==================================================================
// UsersConnectLCRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Server
{
  public class UsersConnectLCRepositoryImplementer<T> : 
    global::Sungero.Reporting.Server.ReportRepositoryImplementer<T>,
    global::Sungero.ClassModul.IUsersConnectLCRepositoryImplementer<T>
    where T : global::Sungero.ClassModul.IUsersConnectLC 
  {
  }
}

// ==================================================================
// UsersConnectLCQueries.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sungero.ClassModul.Queries
{
  public class UsersConnectLC
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("Sungero.ClassModul.Server.Reports.UsersConnectLC.UsersConnectLCQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
  }
}
